export const NB_NUMBER_INTEGERS_PKMN_ID: number = 4;
export const HTTP_NOT_FOUND_CODE_ERROR: number = 404;
export const MAX_GENERATION: number = 9;

export const FRENCH_GAMES_NAME: { [key: string]: string } = {
    test: "test",
    red: "Pokémon Rouge",
    blue: "Pokémon Bleue",
    yellow: "Pokémon Jaune",
    gold: "Pokémon Or",
    silver: "Pokémon Argent",
    crystal: "Pokémon Crystal",
    sapphire: "Pokémon Saphir",
    ruby: "Pokémon Rubis",
    emerald: "Pokémon Émeraude",
    firered: "Pokémon Rouge feu",
    leafgreen: "Pokémon Vert feuille",
    diamond: "Pokémon Diamant",
    pearl: "Pokémon Perle",
    platinum: "Pokémon Platine",
    heartgold: "Pokémon Or HeartGold",
    soulsilver: "Pokémon Argent SoulSilver",
    white: "Pokémon Blanche",
    black: "Pokémon Noire",
    "black-2": "Pokémon Noire 2",
    "white-2": "Pokémon Blanche 2",
    x: "Pokémon X",
    y: "Pokémon Y",
    "omega-ruby": "Pokémon Rubis Oméga",
    "alpha-sapphire": "Pokémon Saphir Alpha",
    sun: "Pokémon Soleil",
    moon: "Pokémon Lune",
    "ultra-moon": "Pokémon Ultra-Lune",
    "ultra-sun": "Pokémon Ultra-Soleil",
    sword: "Pokémon Épée",
    shield: "Pokémon Bouclier",
    violet: "Pokémon Violet",
    scarlet: "Pokémon Écarlate",
    "lets-go-eevee": "Pokémon Let's Go, Évoli",
    "lets-go-pikachu": "Pokémon Let's Go, Pikachu",
    "legends-arceus": "Légendes Pokémon : Arceus",
};

export const POKEDEX: { [key: string]: string } = {
    "national": "National",
    "kanto": "Kanto",
    "original-johto": "Johto",
    "updated-johto": "Johto (HGSS)",
    "kalos-central": "Kalos (Centre)",
    "letsgo-kanto": "Kanto (Let's Go)",
    "original-sinnoh": "Sinnoh",
    "extended-sinnoh": "Sinnoh (DEPS)",
    "conquest-gallery": "Conquest",
    "updated-hoenn": "Hoenn (ROSA)",
    "hoenn": "Hoenn",
    "paldea": "Paldea",
    "isle-of-armor": "Isolarmure",
    "galar": "Galar",
    "hisui": "Hisui",
    "kitakami": "Septentria",
    "original-alola": "Alola (SL)",
    "updated-alola": "Alola (USUL)",
    "unova": "Unys",
    "updated-unova": "Unys (N2B2)",
    "kalos-mountain": "Kalos (Monts)",
    "kalos-coastal": "Kalos (Côtes)",
    "crown-tundra": "Courroneige",
    "original-melemele": "Ile Mele-Mele",
    "updated-melemele": "Ile Mele-Mele (USUL)",
    "original-akala": "Ile d'Akala",
    "updated-akala": "Ile d'Akala (USUL)",
    "original-ulaula": "Ile d'Ula-Ula",
    "updated-ulaula": "Ile d'Ula-Ula (USUL)",
    "original-poni": "Ile de Poni",
    "updated-poni": "Ile de Poni (USUL)",
}
