import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Not found",
  description: "Generated by create next app",
};

export default () => {
    return (
        <p>Hello</p>
    )
}